### ISSUE TITLE
Implement Player LEDs

### ISSUE THREAD

**Issue by FeralAI** [FeralAI/GP2040#19]
Add support for parsing USB out reports for player LED status.

**Comment by jbarket** [comment]
Here's an example for XInput ala Xbox 360 controllers: https://github.com/dmadison/ArduinoXInput

**Comment by FeralAI** [comment]
PWM PLEDs are working with XInput in v0.3.1. Still need to integrate with RGB LEDs and implement for Switch reports.

**Comment by FeralAI** [comment]
RGB LEDs are implemented for XInput.

**Comment by FeralAI** [comment]
Player LED implementation for other platforms will require updates to the USB descriptors in the MPG library.

**Comment by jbarket** [comment]
I think this is effectively closed in favor of other tickets specific to the other platforms we want to add support to. Thoughts?

**Comment by FeralAI** [comment]
I'm fine with closing this one as I didn't intend to get back to it for a while. If someone wants to take on another specific platform for player LEDs, another issue can be opened to track it.
