### ISSUE TITLE
Emulate analog sticks output with dpad

### ISSUE THREAD

**Issue by megablue** [FeralAI/GP2040#53]
say you are able to hold down a layer button to temporarily enable the dpad buttons to emulate analog stick(s) output.
or a dip switch to change switch to analog stick(L/R) emulation.

**Comment by FeralAI** [comment]
There exists an option to toggle LS/RS emulation modes: https://gp2040.info/#/usage?id=d-pad-modes

Regarding holding a layer button to toggle an input, that feature request is captured in #49.

For the DIP switch option, that is being considered in #34.

**Comment by megablue** [comment]
oh i did not know. thanks!
