### ISSUE TITLE
Sponsor for analog support

### ISSUE THREAD

**Issue by Oneil974** [FeralAI/GP2040#54]
Hello,

Could it be possible to become a sponsor for feature development ? In particularly for analog support.

Thanks

**Comment by FeralAI** [comment]
I'm open to sponsored development of features. I don't have a process for handling that right now, but we could discuss your requirements and see how they align with my current thoughts for analog support. Best way to discuss is hit me up on the OpenStick Discord server: https://discord.gg/V5qZS4vdUY

**Comment by FeralAI** [comment]
Work is currently in progress and being tracked in #5. Closing this to clean up the issue list.
