### ISSUE TITLE
Arcade stick unresponsive on PC and Switch with GP2040 - any advice?

### ISSUE THREAD

**Issue by Klatrymadon** [FeralAI/GP2040#67]
Hi there,

I bought a HRAP3 on eBay with the Pi Pico board and GP2040 pre-installed, and it is currently unresponsive on PC, MiSTer and Switch, save for the L3 and R3 buttons, which light up when I test the stick under 'game controllers' on PC. The HRAP shows up as an Xbox 360 controller on PC, a console the firmware doesn't support as far as I'm aware, so I'm wondering if this is an issue with the xinput/dinput/console settings - could you please let me know how to switch between these without opening up the stick, if possible? I've tried uninstalling the device on my PC and seeing if I can get it to register as a generic controller instead, but this didn't help. Is there anything else I can try? (I'm completely unfamiliar with GP2040 itself, but would be up for reinstalling it and doing some tinkering if necessary - please point me in the right direction!)

Thank you very much for your help!

Mike

**Comment by Konsolkongen** [comment]
Try this:
https://gp2040.info/#/usage?id=input-modes

**Comment by Klatrymadon** [comment]
Thanks for your reply! Sadly, I tried this with every button on the stick and on every compatible machine I have (since the Brook UFB changes modes the same way), but I was still seeing no response from anything but the L3 and R3 buttons. 

I didn't have long to test it, but the stick seemed to be working fine when I first opened it, so I'm a bit stumped...

**Comment by jbarket** [comment]
So if it shows as a 360 controller, that’s XInput mode. It’s generally the best for use on PC (in my opinion). If the other buttons aren’t working, my first guess would be that they’re disconnected. It’s possible they were loose and something popped off. If you lost a ground connector, that could cause multiple buttons to stop responding at once.

**Comment by Klatrymadon** [comment]
Thank you! Yeah, I just need to get in there and have a look around. I was hoping there might be other avenues to explore, as the old HRAP bodies are a nightmare to open and put back together, but this one could definitely have been thrown around a lot in the post!

**Comment by jbarket** [comment]
No worries! Glad you figured it out.
